name: strawlab

channels:
  - conda-forge
  - defaults

dependencies:

  - conda-forge::python=2
  - conda-forge::future=0.16.0
  - conda-forge::numpy=1.15.2
  - conda-forge::pandas=0.23.4
  - conda-forge::matplotlib=2
  - conda-forge::seaborn=0.9.0
  - conda-forge::humanize=0.5.1
  - conda-forge::requests=2.19.1

  # For jagged (blosc might fail to compile if installed from pypi)
  - conda-forge::blosc=1.14.4
  - conda-forge::bloscpack=0.13.0

  - pip:
    - whatami>=5.1.15
    - jagged>=0.1.0
    - "-e ."
